import { create } from "zustand";

export const useAuthStore = create((set) => ({
  user: {
    id: "user-1",
    email: "alex@escrowflow.com",
    name: "Alex Morgan",
    avatar: null,
    role: "buyer",
  },
  isAuthenticated: true,
  login: (userData) => set({ user: userData, isAuthenticated: true }),
  logout: () => set({ user: null, isAuthenticated: false }),
}));

export const useUIStore = create((set) => ({
  sidebarOpen: true,
  commandPaletteOpen: false,
  aiPanelOpen: false,
  theme: "dark",
  toggleSidebar: () => set((s) => ({ sidebarOpen: !s.sidebarOpen })),
  toggleCommandPalette: () => set((s) => ({ commandPaletteOpen: !s.commandPaletteOpen })),
  setCommandPaletteOpen: (open) => set({ commandPaletteOpen: open }),
  toggleAIPanel: () => set((s) => ({ aiPanelOpen: !s.aiPanelOpen })),
  setAIPanelOpen: (open) => set({ aiPanelOpen: open }),
}));

export const useEscrowStore = create((set, get) => ({
  escrows: [
    {
      id: "esc-001",
      title: "E-Commerce Platform Redesign",
      description: "Complete redesign of the storefront with modern UI, payment integration, and admin dashboard.",
      buyer: { id: "user-1", name: "Alex Morgan" },
      seller: { id: "user-2", name: "Sarah Chen" },
      arbitrator: { id: "user-3", name: "Mike Torres" },
      amount: 12500,
      funded: 12500,
      released: 3750,
      status: "in_progress",
      category: "Web Development",
      riskScore: 12,
      createdAt: new Date(Date.now() - 7 * 86400000).toISOString(),
      deadline: new Date(Date.now() + 30 * 86400000).toISOString(),
      milestones: [
        { id: "m1", title: "Wireframes & Design System", amount: 3750, status: "approved", completedAt: new Date(Date.now() - 2 * 86400000).toISOString() },
        { id: "m2", title: "Frontend Development", amount: 5000, status: "submitted", completedAt: null },
        { id: "m3", title: "Backend Integration & QA", amount: 3750, status: "pending", completedAt: null },
      ],
    },
    {
      id: "esc-002",
      title: "Mobile App MVP (iOS + Android)",
      description: "Cross-platform mobile app for fitness tracking with social features and gamification.",
      buyer: { id: "user-1", name: "Alex Morgan" },
      seller: { id: "user-4", name: "Priya Sharma" },
      arbitrator: null,
      amount: 25000,
      funded: 25000,
      released: 0,
      status: "funded",
      category: "Mobile Development",
      riskScore: 28,
      createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
      deadline: new Date(Date.now() + 60 * 86400000).toISOString(),
      milestones: [
        { id: "m4", title: "UI/UX Design", amount: 5000, status: "pending", completedAt: null },
        { id: "m5", title: "Core Features", amount: 12000, status: "pending", completedAt: null },
        { id: "m6", title: "Testing & Launch", amount: 8000, status: "pending", completedAt: null },
      ],
    },
    {
      id: "esc-003",
      title: "Smart Contract Audit",
      description: "Full security audit of DeFi protocol smart contracts on Ethereum.",
      buyer: { id: "user-5", name: "DeFi Labs" },
      seller: { id: "user-1", name: "Alex Morgan" },
      arbitrator: { id: "user-3", name: "Mike Torres" },
      amount: 8000,
      funded: 8000,
      released: 8000,
      status: "released",
      category: "Smart Contracts",
      riskScore: 5,
      createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
      deadline: new Date(Date.now() - 5 * 86400000).toISOString(),
      milestones: [
        { id: "m7", title: "Initial Review", amount: 3000, status: "approved", completedAt: new Date(Date.now() - 15 * 86400000).toISOString() },
        { id: "m8", title: "Deep Audit + Report", amount: 5000, status: "approved", completedAt: new Date(Date.now() - 7 * 86400000).toISOString() },
      ],
    },
    {
      id: "esc-004",
      title: "Brand Identity Package",
      description: "Logo, color palette, typography, and brand guidelines for tech startup.",
      buyer: { id: "user-1", name: "Alex Morgan" },
      seller: { id: "user-6", name: "Luna Design Co" },
      arbitrator: null,
      amount: 3500,
      funded: 0,
      released: 0,
      status: "created",
      category: "Graphic Design",
      riskScore: 45,
      createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
      deadline: new Date(Date.now() + 14 * 86400000).toISOString(),
      milestones: [
        { id: "m9", title: "Concept Exploration", amount: 1500, status: "pending", completedAt: null },
        { id: "m10", title: "Final Deliverables", amount: 2000, status: "pending", completedAt: null },
      ],
    },
  ],
  activities: [
    { id: "a1", type: "milestone_approved", escrowId: "esc-001", message: "Milestone 'Wireframes' approved — $3,750 released", time: new Date(Date.now() - 2 * 3600000).toISOString() },
    { id: "a2", type: "milestone_submitted", escrowId: "esc-001", message: "Sarah Chen submitted 'Frontend Development' for review", time: new Date(Date.now() - 5 * 3600000).toISOString() },
    { id: "a3", type: "escrow_funded", escrowId: "esc-002", message: "Escrow funded — $25,000 locked for Mobile App MVP", time: new Date(Date.now() - 48 * 3600000).toISOString() },
    { id: "a4", type: "escrow_created", escrowId: "esc-004", message: "New escrow created — Brand Identity Package", time: new Date(Date.now() - 24 * 3600000).toISOString() },
    { id: "a5", type: "escrow_released", escrowId: "esc-003", message: "All funds released for Smart Contract Audit", time: new Date(Date.now() - 7 * 86400000).toISOString() },
  ],
  getEscrow: (id) => get().escrows.find((e) => e.id === id),
  updateEscrowStatus: (id, status) =>
    set((s) => ({ escrows: s.escrows.map((e) => (e.id === id ? { ...e, status } : e)) })),
}));
